version: 2
before:
  hooks:
    - go mod tidy
builds:
  - main: ./cmd/codeowners
    ldflags:
      - -X main.version={{.Version}}
    env:
      - CGO_ENABLED=0
checksum:
  name_template: "checksums.txt"
dockers_v2:
  - image:
      - "gcr.io/winebarrel/kap"
    tags:
      - "{{ .Version }}"
      - latest
    platforms:
      - linux/amd64
      - linux/arm64
